---
- include_tasks: is_systemd.yml

# Variable configuration.
- include_tasks: variables.yml


- name: Ensure Build Tools Python libraries are installed.
  apt:
    name: "{{ build_python_library }}"
    state: present

- name: Ensure Build Tools packages are installed.
  apt:
    name: "{{ build_packages }}"
    state: present

